# Site settings
title: Lior Deutsch's Blog
email: 
description: "add description"
baseurl: ""
url: "http://liordeutsch.github.io"
twitter_username: lior_de
github_username:  sliorde

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge